name: Devops Angular

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jonne-kiukas"
          heroku_email: "jonne.kiukas@student.lab.fi"
          remote_branch: master  
          usedocker: true
